name: Build and Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Build
        run: make

      - name: Rename
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            mv program program-linux_x64-${{ github.ref_name }}
          elif [ ${{ matrix.os }} == 'windows-latest' ]; then
            rename program program-win_x64-${{ github.ref_name }}
          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
            mv program program-macos_x64-${{ github.ref_name }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: program
          path: ./
          retention-days: 1

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: program

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          draft: true
          prerelease: false
          artifacts: program*
