name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Build
        run: make
  
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

      steps:
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          artifacts: "program"

  upload_artifacts:
    name: Upload artifacts
    runs-on: ubuntu-latest

      steps:
        id: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: program
          path: ./program


