name: Build and Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          pattern: program*
          path: ./
        
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.0
        with:
          pattern: program*
          path: ./
    
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          artifacts: "program"
